In [52]:
import pandas as pd

pd.set_option('display.max_columns',100) ## Set display limit for the columns 
pd.set_option('display.max_info_columns',100)

##pd.set_options.display.max_columns=100

# Dataset Sourcing

In [34]:
raw=pd.read_csv('Data/loan.csv', low_memory=False) ## Importing the Data

In [50]:
raw.head(2) ## Sample check

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,...,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0,Jan-85,1,NaN,NaN,3,0,13648,83.70%,9,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0,Apr-99,5,NaN,NaN,3,0,1687,9.40%,4,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [55]:
raw.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 111 columns):
 #    Column                          Dtype
---   ------                          -----
 0    id                              int64
 1    member_id                       int64
 2    loan_amnt                       int64
 3    funded_amnt                     int64
 4    funded_amnt_inv                 float64
 5    term                            object
 6    int_rate                        object
 7    installment                     float64
 8    grade                           object
 9    sub_grade                       object
 10   emp_title                       object
 11   emp_length                      object
 12   home_ownership                  object
 13   annual_inc                      float64
 14   verification_status             object
 15   issue_d                         object
 16   loan_status                     object
 17   pymnt_plan                      object
 18   url                             object
 19   desc                            object
 20   purpose                         object
 21   title                           object
 22   zip_code                        object
 23   addr_state                      object
 24   dti                             float64
 25   delinq_2yrs                     int64
 26   earliest_cr_line                object
 27   inq_last_6mths                  int64
 28   mths_since_last_delinq          float64
 29   mths_since_last_record          float64
 30   open_acc                        int64
 31   pub_rec                         int64
 32   revol_bal                       int64
 33   revol_util                      object
 34   total_acc                       int64
 35   initial_list_status             object
 36   out_prncp                       float64
 37   out_prncp_inv                   float64
 38   total_pymnt                     float64
 39   total_pymnt_inv                 float64
 40   total_rec_prncp                 float64
 41   total_rec_int                   float64
 42   total_rec_late_fee              float64
 43   recoveries                      float64
 44   collection_recovery_fee         float64
 45   last_pymnt_d                    object
 46   last_pymnt_amnt                 float64
 47   next_pymnt_d                    object
 48   last_credit_pull_d              object
 49   collections_12_mths_ex_med      float64
 50   mths_since_last_major_derog     float64
 51   policy_code                     int64
 52   application_type                object
 53   annual_inc_joint                float64
 54   dti_joint                       float64
 55   verification_status_joint       float64
 56   acc_now_delinq                  int64
 57   tot_coll_amt                    float64
 58   tot_cur_bal                     float64
 59   open_acc_6m                     float64
 60   open_il_6m                      float64
 61   open_il_12m                     float64
 62   open_il_24m                     float64
 63   mths_since_rcnt_il              float64
 64   total_bal_il                    float64
 65   il_util                         float64
 66   open_rv_12m                     float64
 67   open_rv_24m                     float64
 68   max_bal_bc                      float64
 69   all_util                        float64
 70   total_rev_hi_lim                float64
 71   inq_fi                          float64
 72   total_cu_tl                     float64
 73   inq_last_12m                    float64
 74   acc_open_past_24mths            float64
 75   avg_cur_bal                     float64
 76   bc_open_to_buy                  float64
 77   bc_util                         float64
 78   chargeoff_within_12_mths        float64
 79   delinq_amnt                     int64
 80   mo_sin_old_il_acct              float64
 81   mo_sin_old_rev_tl_op            float64
 82   mo_sin_rcnt_rev_tl_op           float64
 83   mo_sin_rcnt_tl                  float64
 84   mort_acc                        float64
 85   mths_since_recent_bc            float64
 86   mths_since_recent_bc_dlq        float64
 87   mths_since_recent_inq           float64
 88   mths_since_recent_revol_delinq  float64
 89   num_accts_ever_120_pd           float64
 90   num_actv_bc_tl                  float64
 91   num_actv_rev_tl                 float64
 92   num_bc_sats                     float64
 93   num_bc_tl                       float64
 94   num_il_tl                       float64
 95   num_op_rev_tl                   float64
 96   num_rev_accts                   float64
 97   num_rev_tl_bal_gt_0             float64
 98   num_sats                        float64
 99   num_tl_120dpd_2m                float64
 100  num_tl_30dpd                    float64
 101  num_tl_90g_dpd_24m              float64
 102  num_tl_op_past_12m              float64
 103  pct_tl_nvr_dlq                  float64
 104  percent_bc_gt_75                float64
 105  pub_rec_bankruptcies            float64
 106  tax_liens                       float64
 107  tot_hi_cred_lim                 float64
 108  total_bal_ex_mort               float64
 109  total_bc_limit                  float64
 110  total_il_high_credit_limit      float64
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

In [40]:
raw.size

4408587

In [41]:
raw.shape

(39717, 111)

# Data Cleaning

### Removing Null Columns

In [63]:
raw.isnull().sum()

id                                0
member_id                         0
loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
                              ...
tax_liens                        39
tot_hi_cred_lim               39717
total_bal_ex_mort             39717
total_bc_limit                39717
total_il_high_credit_limit    39717
Length: 111, dtype: int64

In [86]:
raw2=raw[[ col for col in raw if (raw[col].count()/len(raw)) >=0.25 ]] ## Removing Columns with null values greater than 25 %
### Another option to remove all null columns raw2=raw.dropna(axis=1,how='all')

In [87]:
raw2.shape

(39717, 55)

In [88]:
raw2.isnull().sum()

id                                0
member_id                         0
loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
term                              0
int_rate                          0
installment                       0
grade                             0
sub_grade                         0
emp_title                      2459
emp_length                     1075
home_ownership                    0
annual_inc                        0
verification_status               0
issue_d                           0
loan_status                       0
pymnt_plan                        0
url                               0
desc                          12940
purpose                           0
title                            11
zip_code                          0
addr_state                        0
dti                               0
delinq_2yrs                       0
earliest_cr_line                  0
inq_last_6mths                    0
mths_since_last_delinq        25682
open_acc                          0
pub_rec                           0
revol_bal                         0
revol_util                       50
total_acc                         0
initial_list_status               0
out_prncp                         0
out_prncp_inv                     0
total_pymnt                       0
total_pymnt_inv                   0
total_rec_prncp                   0
total_rec_int                     0
total_rec_late_fee                0
recoveries                        0
collection_recovery_fee           0
last_pymnt_d                     71
last_pymnt_amnt                   0
last_credit_pull_d                2
collections_12_mths_ex_med       56
policy_code                       0
application_type                  0
acc_now_delinq                    0
chargeoff_within_12_mths         56
delinq_amnt                       0
pub_rec_bankruptcies            697
tax_liens                        39
dtype: int64

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,1077501,1296599,5000,5000,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0,Jan-85,1,NaN,3,0,13648,83.70%,9,f,0.00,0.00,5863.155187,5833.84,5000.00,863.16,0.00,0.00,0.00,Jan-15,171.62,May-16,0.0,1,INDIVIDUAL,0,0.0,0,0.0,0.0
1,1077430,1314167,2500,2500,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0,Apr-99,5,NaN,3,0,1687,9.40%,4,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,Sep-13,0.0,1,INDIVIDUAL,0,0.0,0,0.0,0.0
2,1077175,1313524,2400,2400,2400.0,36 months,15.96%,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,real estate business,606xx,IL,8.72,0,Nov-01,2,NaN,2,0,2956,98.50%,10,f,0.00,0.00,3005.666844,3005.67,2400.00,605.67,0.00,0.00,0.00,Jun-14,649.91,May-16,0.0,1,INDIVIDUAL,0,0.0,0,0.0,0.0
3,1076863,1277178,10000,10000,10000.0,36 months,13.49%,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0,Feb-96,1,35.0,10,0,5598,21%,37,f,0.00,0.00,12231.890000,12231.89,10000.00,2214.92,16.97,0.00,0.00,Jan-15,357.48,Apr-16,0.0,1,INDIVIDUAL,0,0.0,0,0.0,0.0
4,1075358,1311748,3000,3000,3000.0,60 months,12.69%,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://lendingclub.com/browse/loanDetail.acti...,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0,Jan-96,0,38.0,15,0,27783,53.90%,38,f,524.06,524.06,3513.330000,3513.33,2475.94,1037.39,0.00,0.00,0.00,May-16,67.79,May-16,0.0,1,INDIVIDUAL,0,0.0,0,0.0,0.0